Create models.py (db structure)
Cine-Pixel/django-ecommerce pull request #8
Opened 2023-01-24 12:52 UTC by BrunoGomes19

2023-01-24 18:55 UTC, Cine-Pixel requested changes

2023-01-24 18:55 UTC, Cine-Pixel commented on ecommerce/ecommerce/models.py
> +    image = models.ImageField(upload_to='products/')
We can have a separate model for image and create many to one relationship with product. (one product many images)
something like:
```python
class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products/')
```

2023-01-25 11:33 UTC, Cine-Pixel commented
Actually let's just have it as a diagram and we'll write the models in respective django apps.

2023-01-25 18:10 UTC, BrunoGomes19 commented
> s just have it as a diagram and we'll write the models in respective django

2023-01-25 18:10 UTC, closed without merging